language: node_js
node_js:
  - "8.11"

branches:
  only:
    - master

addons:
    chrome: stable

before_script:
  - npm install -g @angular/cli

cache:
    directories:
        - node_modules

script:
  - ng build --prod --aot

deploy:
  provider: heroku
  api-key:
    secure: "694d9602-4335-4a60-b910-92584843c04b"
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master